name: Run JMeter Test

on:
  workflow_dispatch:

jobs:
  run-jmeter:
    runs-on: NARESH-HP-WIN11

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify JMeter Installation
        shell: cmd
        run: |
          "D:\Jmeter\apache-jmeter-5.5\bin\jmeter.bat" -v

      - name: Create Results Folder
        shell: cmd
        run: |
          if not exist results mkdir results

      - name: Execute JMeter Test
        shell: cmd
        run: |
          "D:\Jmeter\apache-jmeter-5.5\bin\jmeter.bat" ^
          -n ^
          -t "%GITHUB_WORKSPACE%\ExamSript.jmx" ^
          -l "%GITHUB_WORKSPACE%\results\results.jtl" ^
          -e ^
          -o "%GITHUB_WORKSPACE%\results\html-report"

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: JMeter-Results
          path: results/
